### ISSUE TITLE
We should name the repos with some consistency - else it's confusing and harder to navigate

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto_emails#29]
We should either rename this repo to `neeto_emails` or rename other repos with a hyphen rather than underscore.

![image](https://user-images.githubusercontent.com/31244999/137260094-cf74986f-11c2-44ae-8a16-3ed2553cb481.png)

And in Gemfile too this inconsistency is visible:
https://github.com/bigbinary/neeto-invisible-web/blob/f143d3fd76a9cc948d06c20e785bc1eb1f4c79b9/Gemfile#L74-L78

The gem is named `neeto_emails` but the upstream repo is named as `neeto-emails`.

Also, when searching for this repo that natural instinct is to search for `neeto_emails` given that it's the gem name. But here we are using `hyphen` for repo name.

@datt _a

Please take a look into this.

cc: @unnitallman @sandip-mane

**Comment by prasanthchaduvula** [comment]
@jaybhoyar _a you can take up this issue

**Comment by chiraggshah** [comment]
@jaybhoyar : Any update on this? If you have not started on it or are busy with notifications task, please let @prasanthchaduvula know and he can assign this to someone else.

**Comment by chiraggshah** [comment]
cc @philson-philip

**Comment by jaybhoyar** [comment]
@chiraggshah This is almost fixed. Only one repo `neeto-course-web` is remaining. I think the PR was closed for some unknown reason. I'll fix it and close this issue asap.

**Comment by jaybhoyar** [comment]
Implemented in all neeto apps where the `neeto_emails` gem is used. 
@chiraggshah _a Please review.
