### ISSUE TITLE
neeto.com in mailer is not visible. Change font color.

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/neeto_emails#34]
<img width="780" alt="Kiwi for Gmail 2021-11-19 15-11-51" src="https://user-images.githubusercontent.com/6805530/142601685-4b5b2980-5624-4b05-b84f-8287b5e5abef.png">

**Comment by chiraggshah** [comment]
@philson-philip _a : Assigning this to you since I see your name as tech lead for neeto_emails. Feel free to re-assign it to someone else if you are not the right person.

**Comment by philson-philip** [comment]
I will check the issue 👍

**Comment by philson-philip** [comment]
This issue was occurred due to the changes in the PR https://github.com/bigbinary/neeto_emails/pull/31. So removing the unnecessary styles to fix the issue.
