### ISSUE TITLE
Fix text color for "Accept Invitation"

### ISSUE THREAD

**Issue by chiraggshah** [bigbinary/neeto_emails#46]
<img width="742" alt="Kiwi for Gmail 2022-01-03 17-00-56" src="https://user-images.githubusercontent.com/6805530/147925841-81612e45-0c96-47c1-a427-22108da1c037.png">

**Comment by philson-philip** [comment]
@philson-philip _a Let me check this issue.

**Comment by philson-philip** [comment]
Will fix this issue with Inky template migration.

**Comment by philson-philip** [comment]
Closing this issue since it is fixed with neetoAuth mailer views migration.
