### ISSUE TITLE
Fix "unknown" Name Issue in Invitation Email Headers

### ISSUE THREAD

**Issue by philson-philip** [bigbinary/neeto_emails#54]
Please check the unknown name rendering issue in invitation emails sent from neetoAuth. Screenshot attached below.
cc: @unnitallman 

<img width="643" alt="Screenshot 2022-01-13 at 3 59 15 PM" src="https://user-images.githubusercontent.com/22117214/149313219-22396812-5824-43b6-a8a5-a4bfddaff50c.png">

**Comment by neerajdotname** [comment]
Replace unknown with the email of the person. Client should pass an email in all the cases. Or in most of the cases.

**Comment by unnitallman** [comment]
I could see that the first_name of this user was saved as `Unknown` hence the email says "Hi unknown".  Couldn't reproduce this. 

Also @neerajdotname if first name is not available, email will be taken. The code is already like that.
