### ISSUE TITLE
Feedback about welcome email

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto_emails#56]
https://www.loom.com/share/0783724bc2e849cebefe65dc65ecd531

**Comment by neerajdotname** [comment]
Ref https://monosnap.com/file/M8ItGhpTBMM2W5hWpPic8s6tjPQKS5

https://monosnap.com/file/Z47YhDVVxsLGAsasiFmDUIzelcsmbP

**Comment by philson-philip** [comment]
@philson-philip _a

**Comment by philson-philip** [comment]
@neerajdotname Can you check this design for the welcome email and comment on it?

<img width="425" alt="Screenshot 2022-03-26 at 4 08 13 PM" src="https://user-images.githubusercontent.com/22117214/160235749-51a70e96-e3cc-45cd-a8e7-dd5da1bf4f06.png">

**Comment by neerajdotname** [comment]
@philson-philip Looks good. The welcome email doesn't need to have `/login` but I think that's not an issue with email per se. We will fix it in `neeto-auth`. @mustafapc19 Can you fix that in neetoAuth.

**Comment by philson-philip** [comment]
@mustafapc19 _a If you have any doubts regarding this we can have a call.

**Comment by neerajdotname** [comment]
@philson-philip @mustafapc19 ping. Please look into it.

**Comment by philson-philip** [comment]
@philson-philip _a
