### ISSUE TITLE
Remove footer by default and a few suggestions

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto_emails#63]
https://www.loom.com/share/b06b60b26f154433a84938276ba7646a

@philson-philip @karthiknmenon Lemme know your thoughts on this.

**Comment by philson-philip** [comment]
@neerajdotname Please check the loom video https://www.loom.com/share/0296d4203cdc45fbb1dc1e9e687057f1

**Comment by neerajdotname** [comment]
@philson-philip https://www.loom.com/share/07f8489f14dc4a3f9f0a5ca250e8dc1d

**Comment by philson-philip** [comment]
@neerajdotname I will make the necessary changes in neeto projects. Thanks

**Comment by philson-philip** [comment]
@neerajdotname I have completed the changes for all the revamped emails in respective neeto projects. **neetoChat** changes are already merged. The rest of the projects will be merged by tomorrow(Feb 14) after testing out the changes.

**Comment by neerajdotname** [comment]
@philson-philip Where are we on this issue for rest of the products. https://monosnap.com/file/PVxVrXgatIJ6VOZvVkIlMW1NeAJXH9

**Comment by philson-philip** [comment]
@neerajdotname Currently I have merged all issues for Feb 15 release. As you shared, **neetoForm** emails are not looking good. **neetoForm** is next in the email revamp roadmap. I will take up the issue tomorrow and complete it asap.

**Comment by neerajdotname** [comment]
@philson-philip Sounds good. 👍
