### ISSUE TITLE
Finalising Subject, Header and Content in neetoChat Emails

### ISSUE THREAD

**Issue by philson-philip** [bigbinary/neeto_emails#67]
@neerajdotname _a I have added the currently used title, content and screenshots in the [Chat wiki page](https://github.com/bigbinary/neeto-chat-web/wiki/Chat-Emails). We need to fix the subjects for each email so that the user receiving emails will get a clear idea about mail before opening it. Can you check it and share your suggestions?

cc: @karthiknmenon @unnitallman

**Comment by neerajdotname** [comment]
@philson-philip I looked at the wiki and it's looking good. I'm sure I'll have some feedback when I see emails for real. However we can close this issue for now. I'll create issue as and when I've feedback.
