### ISSUE TITLE
Displaying org name in the email 

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto_emails#71]
https://www.loom.com/share/7f3e6b2b7e7c44bab71df7c8c061cd8c

@karthiknmenon _a

**Comment by neerajdotname** [comment]
@philson-philip https://www.loom.com/share/817995c80ff64cfe969aa95c0d56c97c

**Comment by philson-philip** [comment]
@philson-philip _a

**Comment by philson-philip** [comment]
@ghousemohamed _a

**Comment by philson-philip** [comment]
This issue is fixed across all neeto products by updating the email prefixer gem. Hence closing the issue.
