### ISSUE TITLE
Fixing email footer

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto_emails#74]
@philson-philip _a I'm in dark in terms of when the footer thing will be fixed for auth and the 5 products that we are going live with.

https://monosnap.com/file/kWtJvJFj43X2FRXeZE1xc0u5Wn4dKc

Can you provide me an estimate of when the footer will be fixed for all the products at product level? Based on that I'll decide if more folks need to be put in to get this thing done soon.

**Comment by philson-philip** [comment]
@neerajdotname Initially we decided to keep footer on neetoAuth emails. Currently we are planning to keep the footer only on marketing emails. I will remove the footer from neetoAuth and push it today itself.

**Comment by philson-philip** [comment]
Fixed this issue in https://github.com/bigbinary/neeto-auth-web/pull/1132. Hence closing this issue.
