### ISSUE TITLE
Populate org name in the bracket

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto_emails#83]
https://monosnap.com/file/TmvIDtqOpo6c9jI2AD9S4gHEv0fo1S

**Comment by philson-philip** [comment]
@philson-philip _a

**Comment by philson-philip** [comment]
@ghousemohamed _a

**Comment by philson-philip** [comment]
This issue is fixed across all neeto products by updating the email prefixer gem. Hence closing the issue.
