### ISSUE TITLE
Increase contrast for the login code

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/neeto_emails#88]
https://www.loom.com/share/99f3bb0177d548a3940b381bc210d6fd

@philson-philip _a

**Comment by neerajdotname** [comment]
@philson-philip Can you take this up https://www.loom.com/share/743bc19a25704c049877385df82aa556

https://photos.app.goo.gl/naSBejjGEKmGEndDA

**Comment by vysaghsekharbb** [comment]
@neerajdotname @philson-philip 

https://app.usebubbles.com/bg2nbkyfBkPC9wJjadg241/color-ratio-in-email-template

New Text Color - #4746B7 (Accent1/Darker(700))
Font-Weight - Semi-Bold from Regular
